[[rules]]
name = "remove_method_with_specific_line"
query = """
(
  (method_declaration
    body: (block
      (expression_statement
        (method_invocation
          object: (method_invocation
            name: (identifier) @whenmethod
            arguments: (argument_list
              (string_literal) @when_argument
            )
          )
          name: (identifier) @thenreturn
          arguments: (argument_list
            (string_literal) @return_argument
          )
        )
      )
    )
  ) @method_declaration
)
(#eq? @whenmethod "when")
(#eq? @when_argument "\\"true\\"")
(#eq? @thenreturn "thenReturn")
(#eq? @return_argument "\\"false\\"")
"""
replace_node = "method_declaration"
replace = ""