[[rules]]
name = "replace_isToggleEnabled_with_boolean_literal"
query = """(
    (if_statement
        condition: (parenthesized_expression
            (method_invocation
                object: (identifier) @boolean_parse_obj
                name: (identifier) @boolean_parse_method
                arguments: (argument_list
                    (method_invocation
                        object: (identifier) @config_obj
                        name: (identifier) @config_get_method
                        arguments: (argument_list
                            (field_access
                                object: (identifier) @config_key_obj
                                field: (identifier) @feature_key
                            )
                        )
                    )
                )
            )
        ) @condition
    )
    (#eq? @boolean_parse_obj "Boolean")
    (#eq? @boolean_parse_method "parseBoolean")
    (#eq? @config_obj "tenantConfiguration")
    (#eq? @config_get_method "get")
    (#eq? @feature_key "FEATURE_SEQUENTIAL_NUMBERS_FOR_WARRANTY")
)
"""
replace_node = "method_invocation"
replace = "@treated"
groups = ["replace_expression_with_boolean_literal"]
holes = ["treated", "stale_flag_name"]