[[rules]]
name = "replace_boolean_parse_with_literal"
query = """
((
(method_invocation
object: (identifier) @object
name: (identifier) @name
arguments: (argument_list
([
                          (method_invocation 
        name : (_) @name1
        arguments: ((argument_list 
                        ([
                          (field_access field: (_)@argument)
                          (_) @argument
                         ])) )
            
    ) @method_invocation
                         
						 ])) 
            
) @method_invocation
)
(#eq? @name1 "get")
(#eq? @object "Boolean")
(#eq? @name "parseBoolean")
(#eq? @argument "@stale_flag_name")
)
"""
replace_node = "method_invocation"
replace = "@treated"
groups = ["replace_expression_with_boolean_literal"]
holes = ["treated", "stale_flag_name"]
